language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
after_success:
  - mvn test javadoc:javadoc jacoco:report coveralls:report