name: Java CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches-ignore: 
      - tag/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.SIGNING_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    - name: GPG user IDs
      run: |
        echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import_gpg.outputs.name }}"
        echo "email:       ${{ steps.import_gpg.outputs.email }}"
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B clean verify jacoco:report --file pom.xml -U -P ci
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 9, 10, 11, 12, 13, 14, 15]
    name: Java ${{ matrix.java }} build
    steps:
    - uses: actions/checkout@v2
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v1
      with:
        git_gpgsign: true
        git_committer_name: bedrin
        git_committer_email: dmitry.bedrin@gmail.com
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml -U -P ci